### ISSUE TITLE
dataplot should not have to be re-run to repeat the plot.

### ISSUE THREAD

**Issue by Philipp-Neubauer** [Philipp-Neubauer/fastinR#18]

**Comment by Philipp-Neubauer** [comment]
done in e9cfe879609973c9ea62e5adf22960a3bfceb5c2

**Comment by fredtal** [comment]
How can I show the plot again without rerunning the nmds?

**Comment by Philipp-Neubauer** [comment]
I added two options,

keep=T,new_plot=T

If you had keep=T on your first run (defaults to true now) then using
new_plot=F the next time won't re-run the NMDS. I hope. Note that the
new_plot options defaults to TRUE so you'll have to tell it to use the old
NMDS.

On Thu, Jul 16, 2015 at 5:02 AM, fredtal <notifications@github.com> wrote:

> How can I show the plot again without rerunning the nmds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Philipp-Neubauer/fastinR/issues/18#issuecomment-121680450>
> .
>



-- 
Phil
