### ISSUE TITLE
Check for negative values in preds / preys matrices?

### ISSUE THREAD

**Issue by fredtal** [Philipp-Neubauer/fastinR#22]
Do you want to check the preys and preds matrices for negative values and throw an error if they have any, before running the NMDS?

**Comment by Philipp-Neubauer** [comment]
yes indeed - in fact this should go in as a check when the data is first loaded, as it doesn't make sense to start with.

**Comment by Philipp-Neubauer** [comment]
Have fixed this and some other bugs I noticed yesterday. If you now
re-install fastinR from github, it should tell not to put negative FA
values....I hope!

On Fri, Jun 5, 2015 at 10:07 AM, fredtal <notifications@github.com> wrote:

> Do you want to check the preys and preds matrices for negative values and
> throw an error if they have any, before running the NMDS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Philipp-Neubauer/fastinR/issues/22>.
>



-- 
Phil
